//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arduino_Arayuz1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class arduinoEntities : DbContext
    {
        public arduinoEntities()
            : base("name=arduinoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblesik> tblesik { get; set; }
        public virtual DbSet<tblsensör> tblsensör { get; set; }
    
        public virtual ObjectResult<birlestirme_Result> birlestirme()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<birlestirme_Result>("birlestirme");
        }
    }
}
